# Generated by Django 5.0.1 on 2024-01-24 20:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_customuser_native_name_customuser_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                default="default_user.png",
                upload_to=accounts.models.user_directory_path,
            ),
        ),
    ]
